### ISSUE TITLE
Validator: freemarker variable treated as alias 

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#101]
![image](https://user-images.githubusercontent.com/2098022/45847065-5e207500-bd32-11e8-982e-fbe5bae34642.png)

```
	<#list sids as sid>
	[series]
		alias = ${sid[0]}
		display = false
		label = ${sid[0]}
		value = 0 <#list sid[1]?split(",") as lpar> + value('${lpar}:PX')</#list>
	</#list>
```

**Comment by rodionos** [comment]
Another example:

```
<#list lpars as lpar>

[widget]
  type = chart
  title = [${lpar[2]}] [CEC agent:- ${lpar[0]}] [Frame:- ${lpar[1]}]
  timespan = 7 day

 </#list>
```

**Comment by rodionos** [comment]
![image](https://user-images.githubusercontent.com/2098022/46087706-98b36300-c1b3-11e8-8e45-5106b3f19ec3.png)

**Comment by rodionos** [comment]
The following error remains:

```
	<#list sids as sid>
	[series]
		alias = ${sid[0]}
		display = false
		label = ${sid[0]}
		value = 0 <#list sid[1]?split(",") as lpar> + value('${lpar}:PX')</#list>
	</#list>
```

**Comment by annstriganova** [comment]
For now, freemarker is not validated properly, i.e. there is no list and variable reference checks.
![selection_100](https://user-images.githubusercontent.com/20650874/46350566-b5d9ad00-c65d-11e8-899c-199395662915.png)

Should it be fixed?
