### ISSUE TITLE
Add light icon for dark UI theme

### ISSUE THREAD

**Issue by VeselovAlex** [axibase/axibase-charts-vscode#128]
Currently we have only a dark variant of icon, which is almost invisible in editor with dark theme like 'Solarized Dark'. 

* Default Dark
![image](https://user-images.githubusercontent.com/3617329/45943075-97383e00-bfed-11e8-8142-3c662cc16949.png)

* Solarized Dark
![image](https://user-images.githubusercontent.com/3617329/45943026-6821cc80-bfed-11e8-8ab4-8f4c25023dcc.png)

* Monokai
![image](https://user-images.githubusercontent.com/3617329/45943055-87205e80-bfed-11e8-94af-e244bd4f6606.png)

**Comment by kirmanak** [comment]
Done in #129
