### ISSUE TITLE
Any references or collision with SpellChecker

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#13]
Click to Manage extension takes the user to SpellChecker config.

![image](https://user-images.githubusercontent.com/2098022/45500008-3bb4b780-b786-11e8-9c31-fe7a20b7e923.png)

![image](https://user-images.githubusercontent.com/2098022/45500043-5c7d0d00-b786-11e8-9821-889f001c7737.png)

**Comment by kirmanak** [comment]
Because this button is provided by SpellChecker and is not connected to our extension. Open another file (`*.ts`, `*.html`, `*.md`), you'll see same button with same behaviour.
