### ISSUE TITLE
Validator: duplicate error not raised

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#140]
```
[widget]
  type = gauge
  mode = half
    mode=half
```

There is no error, but setting doesn't support multi-line any any widget.

**Comment by kirmanak** [comment]
@rodionos I thought it [does support](https://github.com/kirmanak/Axibase-Charts-Syntax/issues/175). Should I make it one-line again?

**Comment by rodionos** [comment]
Settings that support multi-line are those that concatenate values, for example:

```
caption = a-
caption = b+
```

This translates into `a-\nb+`
