### ISSUE TITLE
Enable SSL certificate checks

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#15]
Right now we login from nodejs with disabled SSL checks, but we can't disable them in the browser unelss VScode is started with `code --ignore-certificate-errors`.

Disable SSL checks only if VSCode is also started with `code --ignore-certificate-errors`.
In regular mode, login into Axibase server should fail if the cert is self-signed. Display appropriate error.

**Comment by unrealwork** [comment]
SSL certificate checks added in #24.
