### ISSUE TITLE
Validator: No error raised for empty settings.

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#153]
Validator raises no error when any of the following settings are declared with no argument:

`type = chart`

`[widget]`

* `vertical-grid`
* `pointer-position`
* `current-period-style`
* `forecast-style` (Also, does not check if there is a forecast to stylize)
* `display`
* `series-type`

`[threshold]`

* `color`
* `value`

**Comment by kghamilton89** [comment]
`type = gauge`

* `thresholds`
* `colors`
* `gradient-intensity`
* `caption`
* `caption-style`
* `format-tip`
* `format-axis`
* `format-counter`

**Comment by kghamilton89** [comment]
`type = bar`

`[widget]`

* `group`
* `colors`
* `rotate-ticks`
* `sort`

`[column]`

* `column-alert-expression`
* `column-alert-style` (also, no verification if `column-alert-expression` is set, when using CAS setting)
* `column-label-format`

`[series]`

* `alert-expression`
* `alert-style` (Also, no verification if `alert-expression` is set as well)

**Comment by kghamilton89** [comment]
`type = box`

* `rotate-ticks`

**Comment by kghamilton89** [comment]
`type = calendar`

`[widget]`

* `gradient-count`
* `sort`

`[series]`

* `sort`

**Comment by kghamilton89** [comment]
`type = treemap`

`[series]`

* `size`
* `thresholds`
* `color`

`[other]`

* `size`
* `color`

**Comment by kghamilton89** [comment]
`type = graph`

`[widget]`

* `node-alert-style` (also no check as to whether `alert-expression` is defined)
* `link-alert-style` (also no check as to whether `alert-expression` is defined)
* `link-thresholds`
* `link-colors`
* `link-widths`
* `node-thresholds`
* `node-colors`
* `padding`
* `link-color-range`

`[node]`

* `id` (this is a required setting so `[node]` should be flagged as well, the same way that `[series]` is flagged when `entity` or `metric` are not declared.)
* `parent`
* `alert-style` (also no check as to whether `alert-expression` is defined)
* `tooltip`

`[link]`

* `id`
* `nodes`
* `alert-style` (same problem as all `alert-style` settings)
* `tooltip`

`[series]`

* `nodes`
* `links`

**Comment by kghamilton89** [comment]
`type = console`

* `rule`
* `on-click`
* `row-style`
* `sort`

**Comment by kghamilton89** [comment]
`type = property`

`[widget]`

* `hide-column`

`[column]`

* `key`
* `tag`
* `value`
* `format`

`[property]`

* `type`

**Comment by annstriganova** [comment]
@rodionos , Should we allow empty script, i.e. no error for the following

```ls
script = 
```
I think, it would be better to forbid it.

**Comment by rodionos** [comment]
Yes, we could raise error if `script = ` is empty.

**Comment by annstriganova** [comment]
@rodionos , what about this https://github.com/axibase/charts/blob/master/configuration/inheritance.md#resetting-inheritance.
What needs to be fixed, documentation or plugin?

**Comment by rodionos** [comment]
@annstriganova - I need to think about it and discuss it with AV.
