### ISSUE TITLE
Validator: `series` flagged as unknown setting.

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#164]
When `mode = graph` there is a setting `series` which may be declared at the `[node]` and/or `[link]` level.

When declared:

```
[node]
  series = example
```

**OR**

```
[link]
  series = example
```

Validator flags the setting as unknown.

**Comment by rodionos** [comment]
@kghamilton89 - please share a link to a working chartlab example

**Comment by rodionos** [comment]
Fixed in the latest plugin.
