### ISSUE TITLE
`expand-panels` contains erroneous options and flags legitimate settings.

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#170]
* `expand-panels`: Possible values: `compact`, `none`, `all`.
* Plugin recommends `all`, `hover`, `true`, `false`.

**Comment by kghamilton89** [comment]
https://apps.axibase.com/chartlab/e9e8cd37

**Comment by rodionos** [comment]
@unrealwork - please investigate first, which settings are actually supported, because the default (hover) is a valid setting.

**Comment by kghamilton89** [comment]
For `display-panels`, `hover` is a valid setting but I don't think it applies to `expand-panels`.

**Comment by unrealwork** [comment]
@kghamilton89 @rodionos 
I looked over sources and define 3 possible behaviors of the setting. It applies when `display-panels` set to any values except `false`.

1. `true` -> shows full panel

2. `false` -> hides the panel

3. other values -> default panel view

[Simple portal](https://apps.axibase.com/chartlab/f8fdfa49/2/) for demo.

**Comment by rodionos** [comment]
Lets document (and check with plugin) the following allowed values for time chart: `false`, `true`, `compact`. Default value: `compact`. 

For bar chart: `false`, `true`, `hover`. Default value: `hover`.

**Comment by kghamilton89** [comment]
On latest plugin version:
* For Bar Chart: `show-panels` accepts all supported arguments -- https://apps.axibase.com/chartlab/393bb551

**Comment by rodionos** [comment]
> For bar chart: false, true, hover. Default value: hover.

That's how we'll document it for bar chart.

**Comment by kghamilton89** [comment]
That's how I've got it written:
"Show chart control panel.<br>Possible values: `false`, `true`, `hover`.<br>Default value: `hover`."

**Comment by kghamilton89** [comment]
I'm still getting an error from the plugin on `expand-panels = compact`.

```ls
[widget]
  title = <code>expand-panels = compact
  type = chart
  expand-panels = compact

  [series]
    entity = nurswgvml007
    metric = cpu_busy
```

https://apps.axibase.com/chartlab/209a449c

**Comment by rodionos** [comment]
This needs Igor's fix. The issue is not closed yet.

**Comment by unrealwork** [comment]
PR: #194

### Conclusion

The setting affects only on a widget with type `chart`.

For a bar chart, we can't control panels mode with the setting.

In the case of `chart` type, there are three available behaviors that apply when `display-panels` is set to `true` or `hover`

| Setting Value | Behavior |
| --- | --- |
| `all`,`true` | Full mode of panels |
| `auto`, `default`, `compact` | Compact and **default** mode of panels |
| `none`, `false` | panels don't display |

**Default** behavior: Compact mode.

Demo portal: https://apps.axibase.com/chartlab/f0dcb2c0/2/

**Comment by kghamilton89** [comment]
Plugin works as expected.

**Comment by rodionos** [comment]
@kghamilton89 - please update docs based on prior investigation by @unrealwork 

1) Bar chart does NOT support this setting.
2) Time chart: `expand-panels` possible values: `false`, `compact`, `true`. Default is `compact`.

**Comment by kghamilton89** [comment]
@rodionos 
* Bar Chart docs at the moment contain only [`show-panels`](https://github.com/axibase/charts/blob/7daa984bd8f2c3d0e3b06f9ef466c626ddc219b4/widgets/bar-chart/README.md#display-panels), no `expand-panels` setting there.
* Time Chart updated to only show `false`, `compact`, and `true` options.
