### ISSUE TITLE
Validator: `statistics` flags legitimate settings as invalid.

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#171]
Legitimate settings:
* `statistic = average`
* `statistic = maximum`
* `statistic = minimum`

All flagged by plugin as invalid. 

https://apps.axibase.com/chartlab/6d9a3153

When `data-type = statistic` **AND** `statistics = detail`, plugin flags the settings, despite its necessity.

https://apps.axibase.com/chartlab/ebd90c87

**Comment by rodionos** [comment]
These are aliases to avg, min, and max and while currently allowed and applied, they maybe be discontinued. It's better to raise error in this case.
