### ISSUE TITLE
Validator: flags configurations with multiple `value` settings for one series.

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#172]
ChartLab supports multiple `value` settings for one series (see example).

Plugin flags second `value` setting with "`value` setting is already defined."

https://apps.axibase.com/chartlab/e11254b7

**Comment by kghamilton89** [comment]
This error also occurs when we try to assign each widget a unique title, multiple `title` settings within the same `[group]` are flagged.

https://apps.axibase.com/chartlab/76515697

**Comment by kghamilton89** [comment]
This error also occurs when we try to assign multiple caption settings.

https://apps.axibase.com/chartlab/1436de22

**Comment by rodionos** [comment]
While the charts support multi-line value settings, this is prone to errors. It's better to alert user so that the value expression is refactored in one line:

```javascript
      value = var v = value('s7'); if (v > 50) return v;
```

Update examples in chart docs if necessary.
