### ISSUE TITLE
Validator: Message Overlay configuration incorrectly flagged.

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#173]
Message Overlay configuration: https://apps.axibase.com/chartlab/e14cb99c

Flagged with warning: `label-format` is interpreted as a series tag and is sent to the server. Remove the setting from the `[tags]` section or enclose it double-quotes to suppress the warning.

Doing so disables the desired functionality: https://apps.axibase.com/chartlab/9a80dbda

**Comment by rodionos** [comment]
The warning is correct. By moving settings to a higher level, away from the tags section, the warning is no longer raised, and it works as before.

![image](https://user-images.githubusercontent.com/2098022/46783370-a976e380-cd32-11e8-81cc-9d11bd47f3d9.png)
