### ISSUE TITLE
Multiline style validation error

### ISSUE THREAD

**Issue by raipc** [axibase/axibase-charts-vscode#18]
![screenshot 2018-09-14_15-46-13](https://user-images.githubusercontent.com/2247781/45551265-fe0f6780-b835-11e8-9874-63d422d6ddd9.png)

**Comment by rodionos** [comment]
For script, lets keep the message, make it a warning and display:

```
Multi-line settings are deprecated. 
Group multiple settings into blocks:

script
   
endscript
```

Check with AV, if endstyle is supported?

**Comment by kirmanak** [comment]
Multiline style is fixed, created a separate issue for the deprecation message #34
