### ISSUE TITLE
False-positive `already defined` match

### ISSUE THREAD

**Issue by raipc** [axibase/axibase-charts-vscode#19]
Title is not an inherited property, so plugin should not warn about inherited title.
I also think that the information about inherited parameters is only useful when values are the same.

![screenshot 2018-09-14_16-09-19](https://user-images.githubusercontent.com/2247781/45552257-03ba7c80-b839-11e8-8389-71dbe1fdc9a6.png)

**Comment by kirmanak** [comment]
Hints about shadowed settings are removed in #27
