### ISSUE TITLE
Validator: `gradient-count` and `color-range` Error

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#192]
When using `gradient-count` setting, multiple colors need to be defined in `color-range` setting to make it work: https://apps.axibase.com/chartlab/780b5d11

If `gradient-count` is specified with `colors` there is no effect: https://apps.axibase.com/chartlab/895ad97f

If `gradient-count` is specified with **one** color in `color-range`, there is no effect: https://apps.axibase.com/chartlab/af1cb7cb

However, plugin alerts when using multiple values in `color-range` setting such as that in the first example here: `color-range =  green, red`

**Comment by kghamilton89** [comment]
Closing this as there is an alternative way to see results by using `thresholds` setting.

**Comment by kghamilton89** [comment]
Source documentation confirms that multiple colors may be set: https://axibase.com/products/axibase-time-series-database/visualization/widgets/calendar-chart-widget/

**Comment by annstriganova** [comment]
Has something in common with #120

**Comment by rodionos** [comment]
https://github.com/axibase/charts/tree/master/widgets/gauge-chart#widget-settings:

1. If mode is sleek, no thresholds and colors are applied. It's just a b/w presentation
2. colors and color-range are mutually exclusive
3. some other settings may not apply to different modes, e.g. ticks not displayed in sleek mode
