### ISSUE TITLE
Validator: Alert Console requires `[series]` section, according to plugin.

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#197]
Alert Console chart may be used without declaring `[series]` section: https://apps.axibase.com/chartlab/84fda148

```ls
[group]
[widget]
    title = <code>source = alert
    type = console
    entity = *
```

Validator flags setting: "Required section `[series]` not declared."

**Comment by rodionos** [comment]
This is fixed in the latest plugin version
