### ISSUE TITLE
Update interval accepts number

### ISSUE THREAD

**Issue by raipc** [axibase/axibase-charts-vscode#20]
Default unit is seconds.
![screenshot 2018-09-14_16-15-19](https://user-images.githubusercontent.com/2247781/45552384-7d526a80-b839-11e8-952a-5478f9aaf55a.png)

**Comment by rodionos** [comment]
Yes, this is a valid error. 
Although charts will accept the number in seconds, we should raise a WARNING:

```
Specifying the interval in seconds is deprecated. 
Use `count unit` format, for example: `5 minute`. 
```
