### ISSUE TITLE
`class` Error

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#202]
Validator provides unhelpful and invalid alert for correctly defined `class = terminal` setting.

```ls
[widget]
class = terminal
```

https://apps.axibase.com/chartlab/bb9fb175

![image](https://user-images.githubusercontent.com/29099829/46787852-57898a00-cd41-11e8-8c7c-2609a36395ce.png)

**Comment by VeselovAlex** [comment]
Resolved in #205
