### ISSUE TITLE
Alert raised for `[keys]` section 

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#203]
When `type = property` there is a subsection `[keys]`.

Config: https://apps.axibase.com/chartlab/266e32eb
Docs: (See **`[property]` Settings** header) https://axibase.com/products/axibase-time-series-database/visualization/widgets/property-table-widget/

```ls
[keys]
id = eth0
```

Plugin alerts that the section is invalid.

![image](https://user-images.githubusercontent.com/29099829/46788943-fca56200-cd43-11e8-866d-c586b8e61d51.png)

**Comment by VeselovAlex** [comment]
Resolved in #205
