### ISSUE TITLE
Auto keyword not supported

### ISSUE THREAD

**Issue by raipc** [axibase/axibase-charts-vscode#21]
Find out what parameters accept auto as valid value.
![screenshot 2018-09-14_16-16-43](https://user-images.githubusercontent.com/2247781/45552501-ca364100-b839-11e8-98e9-885abfdf5e77.png)

**Comment by kirmanak** [comment]
@rodionos Do all settings with type `interval` support `auto`?

**Comment by annstriganova** [comment]
Checked manually in ChartLab.

### Shared Widget syntax

[`[series]` Settings](https://github.com/axibase/charts/blob/master/widgets/shared/README.md#series-settings)

* `rate`
* `period`
* `group period`
* `downsample-gap`

[Additional [series] Settings](https://github.com/axibase/charts/blob/master/widgets/shared/README.md#additional-series-settings)

* `refresh-interval`
* `retry-refresh-interval`
* `error-refresh-interval`

### Calendar Chart

[[widget] Settings](https://github.com/axibase/charts/blob/master/widgets/calendar-chart/README.md#widget-settings)

* `summarize-period`

### Time Chart

[[widget] Settings](https://github.com/axibase/charts/blob/master/widgets/time-chart/README.md#widget-settings)

* `disconnect-interval`

### Streaming Table

[[widget] Settings](https://github.com/axibase/charts/blob/master/widgets/streaming-table/README.md#widget-settings)

* `expire-time-span`
