### ISSUE TITLE
Portal preview not update on config change

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#214]
1) Open any configuration
2) Click on Preview, wait until chart is shown.
3) Make a change, nothing happens to Preview even if I click twice on the Preview icon

**Comment by rodionos** [comment]
@unrealwork - Igor, did we disable refresh of the portal in an earlier release? I recall that the preview would update instantly once you modify the config.

**Comment by unrealwork** [comment]
@rodionos When we have a file with unsaved changes and click on preview it just tries to load last saved version of the file without the changes.

**Comment by rodionos** [comment]
@unrealwork - I think when we click on Preview, we should render the text in the window even if it's not saved.

**Comment by rodionos** [comment]
Assigning to @unrealwork due to prior experience with the live preview.
