### ISSUE TITLE
Charts / axibase file icon

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#215]
The latest VScode version allows customizing chart icons.

Set appropriate icon for .config files.

![image](https://user-images.githubusercontent.com/2098022/46979785-34613080-d0db-11e8-9722-e4a745b5fa4a.png)

**Comment by annstriganova** [comment]
VSCode doesn't allow to customize file icons, it just applies icons for several most popular file extensions by default.
https://github.com/Microsoft/vscode/issues/4845#issuecomment-419322872

**Comment by rodionos** [comment]
Closing as not supported.
