### ISSUE TITLE
Statistic validation

### ISSUE THREAD

**Issue by raipc** [axibase/axibase-charts-vscode#22]
1. Support percentile(num) value.
2. Change validation message to `statistic must be one of...`
3. Is there a possibility to not split words by linefeed?
![screenshot 2018-09-14_16-18-54](https://user-images.githubusercontent.com/2247781/45552541-ec2fc380-b839-11e8-9b8f-906c85b39b78.png)

**Comment by rodionos** [comment]
charts support both syntax options: `percentile_{n}` and `percentile({n})`. 
change validator to accept either option. In the warning say one of ...  percentile({num}) or percentile_{num} ...

**Comment by kirmanak** [comment]
1. `percentile_{num}` is allowed, whereas `percentile({num}` is not.
2. Done.
3. I've replaced `, ` with `;\n` between array elements. If a message is too big, VSCode adds a scroller automatically.
