### ISSUE TITLE
Out of order [tags] section

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#229]
`type`: any which supports `[tags]` settings
Setting: `[tags]`
Working config: https://apps.axibase.com/chartlab/23d0c74a

Although possible for inheritance purposes, declaring `[tags]` section **before** `[series]` section(s) raises an alert:

![image](https://user-images.githubusercontent.com/29099829/47421085-8879ae00-d788-11e8-9446-ca6a4fbc2f27.png)

**Comment by annstriganova** [comment]
It should be fixed in PR [223](https://github.com/axibase/axibase-charts-vscode/pull/223), I'll retest.

**Comment by annstriganova** [comment]
![selection_001](https://user-images.githubusercontent.com/20650874/47425913-69811900-d794-11e8-898e-b487a3285b0b.png)
