### ISSUE TITLE
Allow one-line script assignment without endscript

### ISSUE THREAD

**Issue by raipc** [axibase/axibase-charts-vscode#23]
![screenshot 2018-09-14_16-25-37](https://user-images.githubusercontent.com/2247781/45552881-f30b0600-b83a-11e8-9ef3-9ee1c4384de3.png)

**Comment by kirmanak** [comment]
I had a test with the absolutely same content [test](https://github.com/axibase/axibase-charts-vscode/blob/ad0a6a475fd8b97fca1d2b6429ca3a04a862ef7d/server/src/test/script.test.ts#L54), though it didn't help me. I've forbidden `endscript` after `script =` in #29, so this issue is fixed.

**Comment by rodionos** [comment]
Provide an example of what is now 'forbidden' and what is allowed for the `script` setting.

**Comment by kirmanak** [comment]
@rodionos it looks like it is not accepted by charts. Remove [here](https://apps.axibase.com/chartlab/01288425/163/) at 74-th line a linefeed and you'll see an alert message, which is not present in the original config.

**Comment by rodionos** [comment]
> it looks like
To avoid decisions on hypothetical statement, perform extra testing.

Check the following syntax in charts:

```
script someJS
someJS
endscript
```

If it is accepted and executed by charts, allow it in validator.
Review charts source for information on how it parses script/endscript to gain certainty.

**Comment by rodionos** [comment]
When sharing examples and testing, create a minimal reproducible example with the least amount of code to proof or disproof a statement.

**Comment by kirmanak** [comment]
@rodionos 
```ls
script someJS
someJS
endscript
```
Is not allowed in charts, whereas allowed in the plugin. 
[example](https://apps.axibase.com/chartlab/39164ff9)

**Comment by kirmanak** [comment]
@rodionos 
Added an error message for statements like 
```ls
script someJs
endscript
```
```ls
script somejs
somejs
endscript
```

`script` is highlighted, error message: `A linefeed character after 'script' keyword is required`

**Comment by rodionos** [comment]
![image](https://user-images.githubusercontent.com/2098022/45617194-330bfc00-ba7a-11e8-887c-3341d3f022ca.png)

This is allowed and accepted by charts. Why is it errored?

**Comment by rodionos** [comment]
This is also allowed, but raises an error.
Change code to raise error ONLY if `script` syntax **breaks** charts.

```
	update-interval = 3 minute
    dialog-maximize = true
    script = defaultChartConfig.timespan = '24=hour'
```

**Comment by kirmanak** [comment]
@rodionos What version of the plugin do you use? The behaviour is not reproducible in the latest (neither in master branch nor marketplace) version. Perhaps, I need the whole configuration to reproduce it or it was fixed already.

**Comment by rodionos** [comment]
Latest from marketplace: 1.0.3

**Comment by rodionos** [comment]
```
[configuration]
  height-units = 2
  width-units = 1
  offset-right = 50
  timespan = 1 day
  legend-position = top
  rotate-ticks = 0
  # change the default color of the calendar period without values to red
  script =  var stylesheet = document.createElement("style");
  script = stylesheet.innerHTML = ".axi-calendarchart .axi-chart-series rect:not([fill]) {fill:red}";
  script = document.head.appendChild(stylesheet);  
```

![image](https://user-images.githubusercontent.com/2098022/45673318-154e9d80-bb33-11e8-86c0-7db88b53caca.png)
