### ISSUE TITLE
Creating Custom Columns (CCC)

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#230]
`type = property`
Setting: Custom column
Working config: https://apps.axibase.com/chartlab/04435f95

Property Table supports the creation of custom columns (for example, one you've used as a sorting parameter), there is no mention of it in [source docs](https://axibase.com/products/axibase-time-series-database/visualization/widgets/property-table-widget/#tab-id-1), so it's also missing from new docs.

@VeselovAlex How does this setting work?

Validator alerts when using such setting:  

![image](https://user-images.githubusercontent.com/29099829/47428226-4c037d80-d79b-11e8-860b-89206c7412aa.png)

**Comment by annstriganova** [comment]
Fixed in PR [232](https://github.com/axibase/axibase-charts-vscode/pull/232)
