### ISSUE TITLE
Validator: duplicate value error

### ISSUE THREAD

**Issue by annstriganova** [axibase/axibase-charts-vscode#237]
![selection_001](https://user-images.githubusercontent.com/20650874/47805466-6cf24280-dd48-11e8-8967-567173061792.png)

```ls
 [series]
      label = swap-used
      value = var t = value('swap-total'), f = value('swap-free');
      value = return t == null || f == null ? null : t - f;
      #value = value('swap-total') - value('swap-free')
```
Working config [here](https://apps.axibase.com/chartlab/7a02ed28).
@rodionos, should we allow such configs?

**Comment by rodionos** [comment]
@annstriganova - do you mean that should we allow value settings consisting of multiple lines? Why not, if charts performs concatination of the value setting and evaluates both lines, then we should allow it.
