### ISSUE TITLE
Validator: tag is allowed in column

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#26]
https://github.com/axibase/charts/tree/master/widgets/shared-table#column-settings

`tag` is allowed:

```
[widget]
  type = property
  title = Connections
  width-units = 3
  timespan = 3 minute
  [column]
      tag = remoteaddress
      label = Remote Address
  [column]
      tag = clientid
      label = Client ID
```

![image](https://user-images.githubusercontent.com/2098022/45555273-015c2080-b841-11e8-9a76-910e218d8916.png)

**Comment by kirmanak** [comment]
[Fixed](https://github.com/axibase/axibase-charts-vscode/commit/9abd95ffe2be06ea03bb03a2472670eee35f9ca4)
