### ISSUE TITLE
Validator: handleCsv() works incorrect

### ISSUE THREAD

**Issue by annstriganova** [axibase/axibase-charts-vscode#267]
![selection_001](https://user-images.githubusercontent.com/20650874/49081897-4517d100-f259-11e8-8f78-599bd7adcff7.png)

```ls
csv rows from https://raw.githubusercontent.com/axibase/atsd-use-cases/master/research/us-visa-refusal/resources/visa-refusal.csv
        
      for row in rows
        [series]
          replace-value = value - @{row[2006]}
          [tags]
            country = @{row.country.replace(",", "\\,")}
      endfor
```

Also fix Formatter. Working config [here](https://apps.axibase.com/chartlab/b00d77c0).

**Comment by VeselovAlex** [comment]
@annstriganova Please, provide link to documentation of this csv syntax. And it is not clear what is actually wrong with CSV formatter. Add more info to description

**Comment by VeselovAlex** [comment]
@PolinaShneider add support of `csv from` syntax ([here](https://axibase.com/docs/charts/syntax/control-structures.html#csv-from-mode))

**Comment by annstriganova** [comment]
CSV parser works in the same way both for Validator and Formatter, therefore the same error is thrown with attempt to format config.
@PolinaShneider, fix Validator first and raise a PR.
