### ISSUE TITLE
Forecast SSA settings: validation

### ISSUE THREAD

**Issue by unrealwork** [axibase/axibase-charts-vscode#279]
- [x] **`forecast-horizon-length`** should accept only positive numbers

- [x] **`forecast-ssa-group-auto-count`** should accept only positive numbers

- [ ] **forecast-horizon-end-time**  should be greater than **`end-time`**

- [x] **forecast-horizon-start-time** will have effect only with one of other horizon settings **forecast-horizon-end-time**,  **forecast-horizon-interval**, **forecast-horizon-length**

- [x] **`forecast-horizon-end-time`, `forecast-horizon-interval`,`forecast-horizon-length`**: should be specified only on of these settings

- [x] **forecast-ssa-decompose-eigentriple-limit** should be bigger than **forecast-ssa-group-auto-count** and be non-negative

- [x] **`forecast-ssa-reconstruct-averaging-function`** accept setting only in upper case

- [x] **forecast-ssa-group-manual-groups** can be applied with **auto-group-count**

- [x] `forecast-ssa-group-manual-groups = 1-10,2-dasd` should be validated for correct group syntax

- [x] `forecast-ssa-group-auto-union = A-B,12312` should be validated for correct group union syntax

- [x] **forecast-ssa-group-auto-union** and **forecast-ssa-group-auto-stack** are mutually exclusive settings

**Comment by annstriganova** [comment]
>  **`forecast-ssa-reconstruct-averaging-function`** accept setting only in upper case

I think it would be better to force upper case in Charts.

**Comment by rodionos** [comment]
The user should be allowed to specify the function names in lower case, e.g. `statistics = avg`, but our parser can convert it to upper case if needed.

**Comment by annstriganova** [comment]
Time settings validation should work for calendar keywords.

**Comment by annstriganova** [comment]
Remaining feature mentioned in #302
