### ISSUE TITLE
ConfigTree: warn if start-time, end-time and timespan are used simultaneously

### ISSUE THREAD

**Issue by annstriganova** [axibase/axibase-charts-vscode#280]
https://github.com/axibase/charts/tree/master/widgets/shared#data-loading

For example,

> When `end-time` is specified, either `start-time` or `timespan` is also required.

**Comment by VeselovAlex** [comment]
`timespan` has default value of 1 hour, and `end-time` is set to `now` if neither `end-time`, nor `start-time` is given. Actually we should warn user if all of `start-time` , `end-time` and `timespan` are set — timespan will be ignored in this case

**Comment by annstriganova** [comment]
@VeselovAlex, you are right.
