### ISSUE TITLE
add-meta scope incorrect

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#287]
add-meta is allowed at widget and series level

![image](https://user-images.githubusercontent.com/2098022/53601840-17c32200-3bbe-11e9-8d88-0885f59bafc1.png)

**Comment by annstriganova** [comment]
Docs need to be fixed, `add-meta` specified at `[widget]` section.
https://github.com/axibase/charts/tree/master/widgets/shared#add-meta
