### ISSUE TITLE
label-format scope incorrect

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#288]
label-format allowed at the series level. I use it to override the format set at one of parent levels.

![image](https://user-images.githubusercontent.com/2098022/53601915-47722a00-3bbe-11e9-8b6b-c9ec12038759.png)

**Comment by annstriganova** [comment]
Docs need to be fixed
https://github.com/axibase/charts/tree/master/widgets/shared#label-format

**Comment by annstriganova** [comment]
Docs updated in PR [148](https://github.com/axibase/charts/pull/148).
