### ISSUE TITLE
Invalid setting 'axis' in [series]

### ISSUE THREAD

**Issue by PolinaShneider** [axibase/axibase-charts-vscode#300]
Code example is taken from documentation: https://trends.axibase.com/e91b896e#

VSCode plugin gives error:
```
Assign series axis.

Example: axis = right
Type: enum
Default value: left
Allowed in section: widget
Allowed in widgets: all

axis setting is not allowed here.
``` 
![invalid-settings](https://user-images.githubusercontent.com/15448200/56598597-71aff900-65fd-11e9-8173-ade7a5afc193.png)

**Comment by annstriganova** [comment]
Fixed in PR [298](https://github.com/axibase/axibase-charts-vscode/pull/298).
Please, re-test with `v1.0.20`.

**Comment by PolinaShneider** [comment]
It works, thanks
