### ISSUE TITLE
Validator error: height-units is allowed in group and widget sections

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#303]
```elm
[configuration]
  offset-right = 50
  height-units = 2
  width-units = 2

[group]

[widget] 
  type = chart 
  timespan = 3 hour 
  width-units = 1.6 
  height-units = 3
  left-units = 0 
  top-units = 0 
  mode = stack
```

https://apps.axibase.com/chartlab/dbf11efa

![image](https://user-images.githubusercontent.com/2098022/56658129-7c709980-66a2-11e9-84b7-b428292facfe.png)

**Comment by annstriganova** [comment]
Also, fix the same issue for `pointer-position`, see `examples/economic.config` and raise a PR with docs fixes
https://github.com/axibase/charts/blob/master/configuration/README.md#height-units
https://github.com/axibase/charts/blob/master/widgets/time-chart/README.md#pointer-position

**Comment by annstriganova** [comment]
Issue assigned to Liza.
