### ISSUE TITLE
Warn if 'stack=true' is used in timechart

### ISSUE THREAD

**Issue by VeselovAlex** [axibase/axibase-charts-vscode#306]
Now `stack=true` is deprecated for timechart. User should use `mode=stack` instead. Please add corresponding validation rule.

Example:
```elm
[widget]
  type = chart
  stack = true
```
should display message: 'Stack is deprecated, use mode = stack instead'

**Comment by VeselovAlex** [comment]
Maybe we should add 'deprecated' field in our settings description map? 
```json
"override": {
  "[widget == 'chart']": {
    "depracated": "This value is depracated in timechart. Use `mode = stack` instead"
  }
}
```

**Comment by PolinaShneider** [comment]
@VeselovAlex 

`stack` setting won't be applied for `type = chart` because it is relevant only for `type = bar`.

See `dictionary.json` for detail
![image](https://user-images.githubusercontent.com/15448200/56892678-0c3e8b00-6a89-11e9-95d5-b64681861912.png)
