### ISSUE TITLE
columns is reported as unknown in property widget

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#322]
```
[widget]
  type = property
  entity = eq
  column-entity = null
  column-time = Time
  columns = connected
  columns = user
  columns = version

  [property]
    type = my-prop
```

However the widgets accepts it and adds a column as expected.

**Comment by annstriganova** [comment]
@PolinaShneider, there are the [docs](https://axibase.com/docs/charts/widgets/shared-table/#columns). Also, refer to Chart docs update in PR [160](https://github.com/axibase/charts/pull/160).
