### ISSUE TITLE
Statement "endsql" does not support auto completion

### ISSUE THREAD

**Issue by Arthasasyan** [axibase/axibase-charts-vscode#325]
![endsql](https://user-images.githubusercontent.com/32041467/58871913-95ba2c00-86cb-11e9-9d8c-a4f511434ce5.png)

However, this statement is highlighted 

![image](https://user-images.githubusercontent.com/32041467/58871990-bda98f80-86cb-11e9-9b3a-dbfdecb4028c.png)

**Comment by PolinaShneider** [comment]
I believe it should behave like a snippet. Creating completions for closing keyword would be strange. What do you think, @annstriganova, @Arthasasyan?

**Comment by annstriganova** [comment]
> I believe it should behave like a snippet.

If you mean something like `completeFor`, then I'm agree.
Please, add method `completeEndKeyword`, use `completeFor` as example.

**Comment by PolinaShneider** [comment]
@annstriganova, should I provide completion for opening control keywords?

Have implemented `completeEndKeyWords` option, but not sure that it alone is quite useful. We still cannot access `if`,`for`,`sql` keywords without `=` sign from autocomplete.

![image](https://user-images.githubusercontent.com/15448200/60342188-7310ef80-99b9-11e9-9357-812a492b249b.png)

**Comment by annstriganova** [comment]
> We still cannot access if,for,sql keywords without = sign from autocomplete.

`if` and `for` must be suggested without `=`, please, fix it.
Also,  create the following snippets:
- [ ] `SQL block`: 
   ```elm
   sql
     SELECT time, entity, value
       FROM "metric_name"
     WHERE datetime >= NOW - 5*MINUTE
   endsql
   ```
- [ ] `Script block`
   ```elm
   script
     window.userFunction = function (value) {
          return Math.round(value / 10) * 10;
     }
   endscript
   ```
Both `sql/script` block `sql/script= ` must be supported in auto completion.

**Comment by PolinaShneider** [comment]
And how about SQL which supports both syntaxes?

**Comment by PolinaShneider** [comment]
@annstriganova, I still have a couple of questions.

1. Do these snippets have to be 'intelligent' like `for` and `if`, which are picking values declared earlier in code, using `var`
2. Should be proposed as autocompletions: 

- `=` syntax if exists
- opening `if|sql|script` etc without snippet
- snippets itself 
- `end${keyword}` in case earlier in code exists such an opening keyword. 

Did I correctly understand you?

**Comment by annstriganova** [comment]
> 1. Do these snippets have to be 'intelligent' like for and if, which are picking values declared earlier in code, using var?

No. For now, it's not necessary.

> 2. Should be proposed as autocompletions: ...

Yes.
