### ISSUE TITLE
[series] auto complete with "=" sign

### ISSUE THREAD

**Issue by Arthasasyan** [axibase/axibase-charts-vscode#327]
When using auto completion for [series], VS Code puts "=" in it
![image](https://user-images.githubusercontent.com/32041467/58887668-b47dea00-86ee-11e9-9800-8356b14aa1a9.png)
I could not find use cases with [series = ... ] section name. Is it an expected behaviour?

**Comment by annstriganova** [comment]
@PolinaShneider, please, check is it still reproduced and fix if necessary.

**Comment by PolinaShneider** [comment]
@annstriganova, this should be done for all sections? Now sections are autocompleted as settings, such as `series =`.

**Comment by PolinaShneider** [comment]
Excuse me, have found that syntax for `series =`: https://apps.axibase.com/chartlab/81319892

**Comment by PolinaShneider** [comment]
So, what is the expected behaviour then? Sections completions was implemented in [this](https://github.com/axibase/axibase-charts-vscode/pull/339) PR. This series is setting in `[link]` section and should be inserted without `[]` brackets

**Comment by annstriganova** [comment]
@PolinaShneider, could we suggest exactly `series` (without `=`) if string starts with `[`?
