### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by annstriganova** [axibase/axibase-charts-vscode#333]
Replace screenshots in [Live Preview](https://github.com/axibase/axibase-charts-vscode/blob/master/README.md#live-preview) section, make emphasis on **Workspace** instead of **User** settings.

**Comment by Arthasasyan** [comment]
I could recommend to also change **Preferences > Settings** on **Live Preview** tab to **File>Preferences > Settings** as it is easier to people who are not familiar with VSCode
