### ISSUE TITLE
Add UDF settings to validator

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#365]
https://apps.axibase.com/chartlab/5066552a

![image](https://user-images.githubusercontent.com/2098022/61647575-4ac59980-acb6-11e9-8449-5907ee947456.png)

`metrics` requires `evaluate-expression`. `evaluate` requires `metrics`
`metrics` is an array of string, comma-separated (`m1 m2` is wrong).

```json
[
    {
        "entity": "gazp_[tqbr]",
        "metric": "quik_tx_all_price",
        "metrics": [
            "quik_tx_all_volume"
        ],
        "evaluate": {
            "expression": "quik_tx_all_price.pair(quik_tx_all_volume, 'entity tags').prod().groupBy('entity').totalSum('5 minute').divide(quik_tx_all_volume.groupBy('entity').totalSum('5 minute'), 'entity')"
        },
        "startDate": "2019-07-22T07:00:00.000Z",
        "endDate": "2019-07-22T16:28:21.799Z"
    }
]
```

**Comment by VeselovAlex** [comment]
1) `metrics` is NOT required: https://apps.axibase.com/chartlab/f27e3d0e. Query always contains at least one metric for calculation.
2) `evaluate-expression` has default value (`union`?), so it is not required https://apps.axibase.com/chartlab/f27e3d0e/2/
