### ISSUE TITLE
False alert on valid start/end time expressions

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#366]
![image](https://user-images.githubusercontent.com/2098022/61689746-6ec5c100-ad30-11e9-8974-b0ba08cf5449.png)

```
  start-time = current_day +  9 hour + 55 minute
  end-time =   current_day + 18 hour + 50 minute
```

**Comment by annstriganova** [comment]
@rodionos, there are no errors at master:
![Selection_001](https://user-images.githubusercontent.com/20650874/62474461-9cd4e780-b7ab-11e9-89df-3798dd895f78.png)

[charts-language-service](https://github.com/axibase/charts-language-service/tree/master/src) is out of date.
