### ISSUE TITLE
ticks warning scope

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#371]
```
[configuration]
  height-units = 2
  width-units = 2
  rotate-ticks = 0
  ticks = 20
```

The above will cause a false info highlight.

1) ticks works for time chart Y axis as well.
2) ticks at [configuration] level may be applied to various times below.
3) fix spelling: `applied`. Check dictionary for spelling errors.

![image](https://user-images.githubusercontent.com/2098022/61965981-33e6b600-afda-11e9-94cd-9b203dd0b935.png)

**Comment by annstriganova** [comment]
Minor docs improvement https://github.com/axibase/charts/pull/167
