### ISSUE TITLE
Preview action and login form

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#4]
1) Show preview icon (same as in markdown) instead of text with tooltip = `Preview charts`. If icon is not possible, show text 'Preview Charts'.

2) Allow https connections with self-signed certificates

![image](https://user-images.githubusercontent.com/2098022/45028485-ea9e1880-b04d-11e8-880f-007934fc33e8.png)

3) Replace login workflow with a single user-friendly form. Instead of URL display fields: 'Protocol', 'Hostname', 'Port', 'Username', 'Password'. Set Protocol to HTTPS, set Port to 8443 by default. Is drop-down possible in this form builder? It would be nice to use it for Protocol.

![image](https://user-images.githubusercontent.com/2098022/45028081-4a93bf80-b04c-11e8-8c9e-81f990e61b3e.png)

Tooltip text (below). Enter connection properties and user credentials. Connection settings will be saved in VSCode extension settings as `axibaseCharts.*` properties. User credentials are not stored on file and are cached in memory for the duration of the session.

**Comment by kirmanak** [comment]
@rodionos 
1. What about copyrights? Can we use their icon?
3. I can't find any VSCode API which allows to create a form. Do you know any extensions with such functional? For example, Git asks for username and password using these input boxes, not a single form.

**Comment by kirmanak** [comment]
@rodionos 

> Connection settings will be saved in VSCode extension settings as axibaseCharts.* properties

So I should save url and username in settings manually? What if the user does not want to save these values?

**Comment by rodionos** [comment]
Use our icon:

![image](https://user-images.githubusercontent.com/2098022/45034068-107fe900-b05f-11e8-8403-e5c3c3e9629b.png)

Instead of form, lets use showQuickPick for protocol, followed by a series of showInputBox for each field separately. So basically split url into multiple settings and use quickpick for protocol.

**Comment by kirmanak** [comment]
@rodionos I've splitted the URL InputBox to an QuickPic for the protocol, an InputBox for the address and an InputBox for the port. Last two InputBox fields have validation.

The error about self-signed certificate was thrown by nodejs https.request() method, which is used to receive the cookie from ATSD. That error is fixed, now we can get cookie from self-signed host. But `vscode.previewHtml` command does not throw an error. it just shows empty page. Don't know how to fix yet.

**Comment by kirmanak** [comment]
@rodionos Icon added in #6

**Comment by rodionos** [comment]
Modify inputs as follows:

* Protocol 

Tooltip: `Choose the protocol to connect to the ATSD server.` 
Values: HTTPS (listed first); HTTP.

* Hostname

Tooltip: `Enter the server hostname or IP address.` 
Value: Display atsd_hostname as the default value.

* Port

Tooltip: `Enter the server port number.`
Value: Display 8443 if protocol is HTTPS and 8088 if protocol is HTTP as the default values.

* Username

Tooltip: `Enter user name.`

* Password

Tooltip: `Enter user password. The password is cached in memory for the duration of the session. To logout from an active session, restart VSCode.`

After this step display a dialog window that offers to store connection properties in VSCode settings.

`Would you like to store connection properties and the user name in VSCode settings?`
Yes / No

If dialog window is not possible, display an information window:

```
To re-use connection properties, except the password, open VSCode settings and add the following properties:

'axibaseCharts.username'

```

Can you display json fragment that user can copy into VSCode settings file?

**Comment by rodionos** [comment]
Lets get rig of all inputs except password.
Just add Protocol, host, etc. other fields with tooltips as described above to settings.
The new settings editor is good enough to use as a form.
If the user clicks on Preview, but one of required settings is missing, return an alert message:

```
Configure connection properties in VSCode > Preferences > Settings. Open Settings, search settings for 'axibase', and enter the requested connection properties.
```

![image](https://user-images.githubusercontent.com/2098022/45173258-4fa16c00-b210-11e8-91e2-52f5091d2edd.png)

**Comment by rodionos** [comment]
Show an informational message on successful login.

```
Connected to {host:port} as {username}.
```

**Comment by kirmanak** [comment]
@rodionos The informational message is shown, addresses of static resources are chosen based on `Server` header (if present and contains "ATSD" case-insensitive then `/web/{js or css}/portal` is used, `/JavaScript/portal/{JavaScript or CSS}` otherwise).

**Comment by rodionos** [comment]
Fixed and working, thx @unrealwork
