### ISSUE TITLE
[tag] section deprecated

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#40]
![image](https://user-images.githubusercontent.com/2098022/45616425-1ec6ff80-ba78-11e8-9d76-f1829bb4195b.png)

```
  [series]
    entity = abc
    metric = free_space
    [tag]
      name = Disk
      value = C:
```

Raise a warning, apply markdown formatting to the suggested snippet:

```
Replace `[tag]` sections with `[tags]`.
Enclose the tag name in double quotes in case it contains special characters.

[tag]
  name = k
  value = v
[tag]
  name = my column
  value = my value

[tags]
  k = v
  "my column" = my value
```

**Comment by unrealwork** [comment]
done in #100

**Comment by rodionos** [comment]
![image](https://user-images.githubusercontent.com/2098022/45916038-e6ecfd00-be67-11e8-968d-cf82572b69eb.png)

We still have two warnings for [tag] - one to replace [tag] with [tags]. This warning is ok, but the remaining error that value will be sent is wrong. It's ok to define tag as name and value.

**Comment by rodionos** [comment]
Sorry, I'm using the old version. I'll delete the extension installed from vscode marker and will install one from master.

**Comment by unrealwork** [comment]
The problem still exists I suppose the error should raise when the tag key has the name `value`.

```
[tags]
  value = a
```
Or is it not correct at all?

**Comment by rodionos** [comment]
```
[tags]
  value = a
```

Do not raise a warning (value interpreted ...) when we use `[tag]` (singular).
Because this is old syntax which is legal:

```
[tag]
  name = tag-name
  value = tag-value
```

For the singular `[tag]` we have a warning saying that old syntax is deprecated, convert to plural `[tags]`.
