### ISSUE TITLE
Setting already defined error

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#41]
```
    thresholds = 0
    thresholds = 60
    thresholds = 80
    thresholds = 100
    colors = green
    colors = orange
    colors = red
```

This displays error 'threshold is already defined'.

1) Does this syntax work in charts?
2) What is the workaround?

If the syntax doesn't work - raise error. Otherwise, warning.
Check on gauge and calendar widgets. A workaround message could be:

```
Replace multiple `thresholds` settings with one:

    thresholds = 0
    thresholds = 60
    thresholds = 80

    thresholds = 0, 60, 80
```

**Comment by kirmanak** [comment]
@rodionos The syntax is correct and it works in charts. Why should I raise a warning and what the warning message would be? 
I believe, I should just mark `thresholds` as a multi-line setting and don't raise anything, is that OK?

**Comment by rodionos** [comment]
I asked questions in earlier comments so that we can make an informed decision based on your research of how these settings actually work. Once we have inputs, we'll decide on what's the best way to handle it.

**Comment by rodionos** [comment]
Raise a warning. The purpose is to discourage the users from anti-patterns that we still support but may drop in the near future.

Warning text:

```
Replace multiple `thresholds` settings with one, for example:

    thresholds = 0
    thresholds = 60
    thresholds = 80

    thresholds = 0, 60, 80
```
