### ISSUE TITLE
Validator: script error

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#45]
![image](https://user-images.githubusercontent.com/2098022/45625110-cb16df00-ba94-11e8-8e4e-7235c25c6a32.png)

**Comment by kirmanak** [comment]
@rodionos Please, update the extension and test again. If that is still reproducible, please, give me the whole configuration.
![script](https://user-images.githubusercontent.com/24299495/45673263-e59f9580-bb32-11e8-8f68-0e6a66577b56.png)

**Comment by rodionos** [comment]
I use the latest version from marketplace 1.0.3.

![image](https://user-images.githubusercontent.com/2098022/45673565-ab82c380-bb33-11e8-8f9c-d35e5b2dbfff.png)

**Comment by kirmanak** [comment]
Confirmed. Problem is the keyword `script` below which is part of the `javascript` keyword.
![script](https://user-images.githubusercontent.com/24299495/45680607-fc021d00-bb43-11e8-8974-6de4756e37f9.png)
