### ISSUE TITLE
Validator: error if value is ternary operator

### ISSUE THREAD

**Issue by annstriganova** [axibase/axibase-charts-vscode#48]
`series-label` [example](https://github.com/axibase/charts/blob/728d73b6ab4d5d67a6b2d76c9c901c2ed5d98a49/widgets/pie-chart/README.md#series-settings).

![selection_099](https://user-images.githubusercontent.com/20650874/45672552-272f4100-bb31-11e8-926b-c013b58495f0.png)

![selection_098](https://user-images.githubusercontent.com/20650874/45672558-29919b00-bb31-11e8-8162-c2b0ef4b353c.png)

```ls
[configuration]
  update-interval = value >= 2000000 ? 1 minute : 2 minute
  series-labels = value >= 2000000 ? 'connected' : 'auto'
```

For example, [`icon-alert-style`](https://github.com/axibase/charts/blob/728d73b6ab4d5d67a6b2d76c9c901c2ed5d98a49/widgets/pie-chart/README.md#icon-and-caption-settings) and [`audio-alert`](https://github.com/axibase/charts/blob/master/configuration/audio-alerts.md#series-settings) doesn't produce any errors.

**Comment by kirmanak** [comment]
@annstriganova Are you sure that `update-interval` accepts JS?

**Comment by annstriganova** [comment]
@kirmanak Looks strange, but there are no errors https://apps.axibase.com/chartlab/38721784/3/

**Comment by annstriganova** [comment]
@kirmanak I guess I'm wrong: no errors and no chart update, for now the issue is relevant only for `series-labels`, but I didn't check other settings.

**Comment by kirmanak** [comment]
@annstriganova `series-labels` type is script now, so I close the issue. Feel free to open a new issue, if you find another wrong validation.
