### ISSUE TITLE
Class setting values

### ISSUE THREAD

**Issue by kirmanak** [axibase/axibase-charts-vscode#55]
`class` accepts `metro`, `detailWidget` as well as `terminal`

**Comment by kirmanak** [comment]
Fixed in #68

**Comment by kirmanak** [comment]
Fix reverted in #70

**Comment by kirmanak** [comment]
The setting should support different sets of values for different widgets:
1. `terminal` for `alert-console`
2. `metro` for `box-chart`
3. `detailWidget` for `property`, `console` and `chart`

**Comment by rodionos** [comment]
This issue is about making enums listed in the warning message display allowed values that are specific to the given widget/section

**Comment by VeselovAlex** [comment]
`detailWidget` is just a hack from one configuration to set css class for widget. Other cases are implemented in #178
