### ISSUE TITLE
Unknown alias

### ISSUE THREAD

**Issue by kirmanak** [axibase/axibase-charts-vscode#77]
![screenshot from 2018-09-19 14-39-23](https://user-images.githubusercontent.com/24299495/45751054-da736500-bc19-11e8-9e73-7fe44cae41de.png)

**Comment by kirmanak** [comment]
Error is not reproducible on master branch

**Comment by rodionos** [comment]
Check if it's reproducible on the latest released version - 1.0.3.

**Comment by kirmanak** [comment]
@rodionos The error was "added" on `issue-52` branch and is fixed already.
