### ISSUE TITLE
Validator: interval warning should be clear

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#86]
![image](https://user-images.githubusercontent.com/2098022/45760191-30ec9d80-bc32-11e8-834f-37c6de46f9cb.png)

```
[configuration]
   width-units = 2
   height-units = 1
   summarize-period = 1 day
   summarize-statistic = avg
   update-interval = 1 seconds
```

```
update-interval should be set as count and unit (singular), for example, 5 minute. Supported units: second, minute, ... (list all that we support).
```

**Comment by annstriganova** [comment]
Is it ok?
![screenscast_20180921_133006](https://user-images.githubusercontent.com/20650874/45876202-a6777b80-bda2-11e8-88ed-401ee98013c4.gif)

Please note the error message has been changed for **all** interval settings.

**Comment by annstriganova** [comment]
![selection_099](https://user-images.githubusercontent.com/20650874/45876327-fd7d5080-bda2-11e8-8605-d02f18150cfe.png)

**Comment by rodionos** [comment]
👍
