### ISSUE TITLE
Validator: join in property widget

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#93]
`join` is allowed in property widget

```
 [widget]
	type = property
	title = Container Properties
    width-units = 0.5
    entity =
    timespan = 1 month
    responsive = false
    join = entity, status
    sort = status_code, startedat
```

**Comment by kirmanak** [comment]
@rodionos According to [charts repo](https://github.com/axibase/charts/tree/master/widgets/property-table#widget-settings) possible values are: `true`, `false`, `entity`. I believe, the error is raised about the type of the setting, not the name. Is `entity, status` allowed value?

**Comment by rodionos** [comment]
This description in repo may be outdated based on issue 1279. Property keys maybe allowed, please search config examples from apps
